---
  Switchport-1/0/3:
    url: 192.168.1.208
    platform: catalyst
    hostname: m_cat9200l-1
    number: 1/0/3
    rport: 1%2F0%2F3 #rest urlencoded format for port#
    enabled: true
    name: uplink-port to MX
    tags: uplink
    type: access
    vlan: 1
    
  Switchport-1/0/4:
    url: 192.168.1.208
    platform: catalyst
    hostname: m_cat9200l-1
    number: 1/0/4
    rport: 1%2F0%2F3 #rest urlencoded format for port#
    enabled: true
    name: uplink-port to MX Spare
    tags: uplink
    type: access
    vlan: 1