---    
  switchport-1:
    serial: Q2HP-2Y42-HXXD
    platform: meraki
    number: 1
    enabled: yes
    name: Uplink-to-MX
    tags: POS
    type: trunk
    vlan: 1
    
  switchport-2:
    serial: Q2HP-2Y42-HXXD
    platform: meraki
    number: 2
    enabled: yes
    name: AP-1
    tags: AP
    type: trunk
    vlan: 1
    
  switchport-3:
    serial: Q2HP-2Y42-HXXD
    platform: meraki
    number: 3
    enabled: yes
    name: Client-PC-1
    tags: clientPC
    type: access
    vlan: 20

  Switchport-4:
    serial: Q2HP-2Y42-HXXD
    platform: meraki
    number: 4
    enabled: yes
    name: IOT-Device-1
    tags: IOT
    type: access
    vlan: 30


