---
host:
  -
    name: "m_cat9200l-1"
    stpmode: "mstp"

interfaces:
#add interfaces with configs different than those defined in the template

svi:
    -
      vlan: 'vlan100'
      description: 'SVI for Vlan100'
      ipaddress: '192.168.100.1 255.255.255.0'
    -
      vlan: 'vlan200'
      description: 'SVI for Vlan100'
      ipaddress: '192.168.200.1 255.255.255.0'

loopbacks:
  -
    int: "loopback0"
    ip: "192.168.1.1"
    mask: "255.255.255.255"

  -
    int: "loopback1"
    ip: "172.16.1.1"
    mask: "255.255.255.255"

bgp:
  bgpasn: "65201"
  bgpNetworks:
    - ip: "10.0.0.2"
      remote_as: "65200"

ospf:
  processid: "1.1.1.1"
  routerid: "192.168.1.1"
  networks:
    -
static:
  -















