---
  interfaces:
    -
      interface: '1'
      description: 'uplink'
      mode: 'trunk'
      vlan: '1'
      portstate: 'true'
    -
      interface: '2'
      description: 'client'
      mode: 'access'
      vlan: '997'
      portstate: 'true'
    -
      interface: '3'
      description: 'client'
      mode: 'access'
      vlan: '997'
      portstate: 'true'

    -
      interface: '4'
      description: 'client'
      mode: 'access'
      vlan: '997'
      portstate: 'true'

    -
      interface: '5'
      description: 'client'
      mode: 'access'
      vlan: '997'
      portstate: 'true'

    -
      interface: '6'
      description: 'client'
      mode: 'access'
      vlan: '997'
      portstate: 'true'

    - interface: '7'
      description: 'client'
      mode: 'access'
      vlan: '997'
      portstate: 'false'

    - interface: '8'
      description: 'client'
      mode: 'access'
      vlan: '997'
      portstate: 'false'

    - interface: '9'
      description: 'trunk'
      mode: 'trunk'
      vlan: '1'
      portstate: 'true'

    - interface: '10'
      description: 'trunk'
      mode: 'trunk'
      vlan: '1'
      portstate: 'false'

  stp:
    priority: ""