---
host:
  name: 'm_ms220-1'

interfaces:
  -
    interface: '6'
    description: 'client - Added by Python'
    mode: 'access'
    vlan: '997'
    portstate: 'true'

  -
    interface: '7'
    description: 'client - Added by Python'
    mode: 'access'
    vlan: '997'
    portstate: 'false'

  -
    interface: '8'
    description: 'client - Added by Python'
    mode: 'access'
    vlan: '997'
    portstate: 'false'

  -
    interface: '9'
    description: 'client - Added by Python'
    mode: 'trunk'
    vlan: '1'
    portstate: 'true'

  -
    interface: '10'
    description: 'trunk-AP'
    mode: 'trunk'
    vlan: '1'
    portstate: 'true'

stp:
  -
    mode: 'rstp'
    priority: ''
