---

###common values for all activities


- name: meraki deployment
  hosts: localhost
  collections:
    - cisco.meraki
    - community.general.cisco_webex
  
  vars_prompt:
    - name: auth_key
      prompt: "Enter your API Key: "
      private: yes

    - name: network_name
      prompt: "Enter the Network Name: "
      private: no

  vars:
    org_name: "{{ org_info.m_org_name }}"
    auth_key: "{{ api_uri.m_auth_key }}"
    roomid: "{{ webex_teams.roomid }}"
    webex_api: "{{ webex_teams.webex_api }}"
    
  vars_files:
    - './vars.yaml'

  tasks:

     - name: include variables for addresses
       include_vars: 
         file: ./{{ network_name|lower }}/mx-vlans.yaml
         name: addresses

     - name: Update VLANs.
       cisco.meraki.meraki_mx_vlan:
         auth_key: "{{ auth_key }}"
         org_name: "{{ org_name }}"
         net_name: "{{ item.value.network_name }}"
         state: present
         vlan_id: "{{ item.value.vlan_id }}"
         name: "{{ item.value.name }}"
         subnet: "{{ item.value.subnet }}"
         appliance_ip: "{{ item.value.default_gw }}"
       delegate_to: localhost
       register: off_addvlan
       ignore_errors: yes
       loop: "{{ lookup('dict', addresses, wantlist=True) }}"

     - name: WebexTeams - add vlans
       community.general.cisco_webex:
         recipient_type: roomId
         recipient_id: "{{ roomid }}"
         msg_type: text
         personal_token: "{{ webex_api }}"
         msg: "Vlans in Network {{ network_name }} have been updated."
    







        
