---

###common values for all activities


- name: meraki deployment
  hosts: localhost
  collections:
    - cisco.meraki
    - community.general.cisco_webex
  
  vars_prompt:
    - name: auth_key
      prompt: "Enter your API Key: "
      private: yes

    - name: network_name
      prompt: "Enter your Network Name: "
      private: no

  vars:
    org_name: "{{ org_info.m_org_name }}"
    auth_key: "{{ api_uri.m_auth_key }}"
    roomid: "{{ webex_teams.roomid }}"
    webex_api: "{{ webex_teams.webex_api }}"
    
  vars_files:
    - './vars.yaml'

  tasks:

    - name: include variables for network specific ssids
      include_vars: 
        file: ./{{ network_name|lower }}/ssid.yaml
        name: ssids
    
    - name: add ssids
      cisco.meraki.meraki_mr_ssid:
        auth_key: "{{ auth_key }}"
        state: present
        org_name: "{{ org_name }}"
        net_name: "{{ item.value.net_name }}"
        name: "{{ item.value.ssid_name }}"
        ip_assignment_mode: "{{ item.value.ip_assignment_mode }}"
        use_vlan_tagging: "{{ item.value.use_vlan_tagging }}"
        default_vlan_id: "{{ item.value.vlan_id }}"
        auth_mode: "{{ item.value.auth_mode }}"
        psk: "{{ item.value.psk }}"
        encryption_mode: "{{ item.value.encryption_mode }}"
        enabled: true
      delegate_to: localhost
      register: off_ssid
      ignore_errors: yes
      loop: "{{ lookup('dict', ssids, wantlist=True) }}"

    - name: WebexTeams - add SSID
      community.general.cisco_webex:
        recipient_type: roomId
        recipient_id: "{{ roomid }}"
        msg_type: text
        personal_token: "{{ webex_api }}"
        msg: "SSIDs in Network {{ network_name }} have been updated."





        
