---

###common values for all activities


- name: meraki deployment
  hosts: localhost
  collections:
    - cisco.meraki
    - community.general.cisco_webex
  
  vars_prompt:
    - name: auth_key
      prompt: "Enter your API Key: "
      private: yes

    - name: network_name
      prompt: "Enter the Network Name: "
      private: no

  vars:
    org_name: "{{ org_info.m_org_name }}"
    auth_key: "{{ api_uri.m_auth_key }}"
    roomid: "{{ webex_teams.roomid }}"
    webex_api: "{{ webex_teams.webex_api }}"
    
  vars_files:
    - './vars.yaml'
    
  tasks:

    - name: include variables for switchports
      include_vars:
        file: ./{{ network_name|lower }}/mswitchports.yaml
        name: switchports

    - name: add switch vlans
      cisco.meraki.meraki_ms_switchport:
        auth_key: "{{ auth_key }}"
        state: present
        serial: "{{ item.value.serial }}"
        number: "{{ item.value.number }}"
        enabled: "{{ item.value.enabled }}"
        name: "{{ item.value.name }}"
        tags: "{{ item.value.tags }}"
        type: "{{ item.value.type }}"
        vlan: "{{ item.value.vlan }}"
      delegate_to: localhost
      register: off_switchports
      ignore_errors: yes
      loop: "{{ lookup('dict', mswitchports, wantlist=True) }}"


    - name: WebexTeams - report on switch ports
      community.general.cisco_webex:
        recipient_type: roomId
        recipient_id: "{{ roomid }}"
        msg_type: text
        personal_token: "{{ webex_api }}"
        msg: "Switchports in Network {{ network_name }} have been updated."




        
