---  
  org_info:
     m_org_name: DevNet

  webex_teams:
     roomid: Y2lzY29zcGFyazovL3VzL1JPT00vNjY5OWZhZDAtNjFhOC0xMWVjLWFhY2UtZjVmYjdiNzIyYWU5     
     webex_api: NzcwYWFhYTAtZGIyNi00OTIwLWJiMjUtYjEzMDhjY2E3NjZjYjJmZGUzOGEtMWU2_PF84_1eb65fdf-9643-417f-9974-ad72cae0e10f

  catalyst:
    uri: 192.168.1.208
    username: meraki	
    password: meraki
     
  api_uri:
     m_api_url:  https://api.meraki.com/api/v1

